[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[start]
cmd = "gunicorn backend.app:create_app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --log-level debug --access-logfile - --error-logfile - --capture-output"
